Update ESRGAN.ipynb
lvl1scans/ESRGAN-colab pull request #1
Opened 2022-04-04 13:39 UTC by Ever4engel

added 4x-AnimeSharp 4x-AnimeSharp-lite.

2022-04-11 22:19 UTC, lvl1scans requested changes
Everything else looks good

2022-04-11 22:19 UTC, lvl1scans commented on ESRGAN.ipynb
> +		"4x-AnimeSharp-lite = True #@param {type: \"boolean\"}\n",
Make this `False`
No need to pre-select the Lite model if full version is already selected.

2022-04-12 01:46 UTC, Ever4engel reviewed
4x-AnimeSharp-lite put to false

2022-04-12 05:17 UTC, lvl1scans approved these changes
Can be merged now

2022-04-12 05:17 UTC, merged